[[language]]
name = "python"
language-servers = [ "ruff", "basedpyright", "pylyzer" ]
auto-format = true
[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
[language-server.ruff]
command = "ruff"
args = ["server"]
[language-server.pylyzer]
command = "pylyzer"
args = ["--server"]
